[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "bundle exec rails db:prepare"
startCommand = "bundle exec rails server -b 0.0.0.0"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
